kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-kafka
  namespace: kafka
  labels:
    type: local
spec:
  storageClassName: generic
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kafka"
# for 05pzoo we seem to need a separate persistent volume definition 
# see: https://apassionatechie.wordpress.com/tag/persistentvolumeclaim-is-not-bound/