kind: PersistentVolume
apiVersion: v1
metadata:
  name: data
  labels:
    type: local
spec:
  storageClassName: generic
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"